---
- name: Assert variables
  ansible.builtin.assert:
    that:
      - ntp is defined
      - ntp.primary_servers is defined
      - ntp.primary_servers | type_debug == 'list'
      - ntp.primary_servers | length > 0
      - ntp.fallback_servers is defined
      - ntp.fallback_servers | type_debug == 'list'
      - ntp.fallback_servers | length > 0
    quiet: true
