---
- name: Assert primary ntp servers
  ansible.builtin.assert:
    that:
      - ntp.primary_servers is defined
      - ntp.primary_servers | type_debug == 'list'
      - ntp.primary_servers | length > 0
    quiet: true

- name: Assert fallback ntp servers
  ansible.builtin.assert:
    that:
      - ntp.fallback_servers is defined
      - ntp.fallback_servers | type_debug == 'list'
      - ntp.fallback_servers | length > 0
    quiet: true
