---
- name: Create dir for systemd-timesyncd config
  ansible.builtin.file:
    path: "{{ timesyncd_conf_dir }}"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy systemd-timesyncd config
  ansible.builtin.template:
    src: local.conf.j2
    dest: "{{ timesyncd_conf_dir }}/local.conf"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart systemd-timesyncd service
