---
pacman_packages:
  - base
  - base-devel
  - bind
  - bluetui
  - bluez
  - bluez-utils
  - chezmoi
  - dunst
  - efibootmgr
  - earlyoom
  - fastfetch
  - fzf
  - git
  - gnupg
  - gopass 
  - grim
  - grub
  - gst-plugin-pipewire
  - htop
  - hyprland
  - hyprpaper
  - intel-media-driver
  - intel-ucode
  - irqbalance
  - iwd
  - kitty
  - less
  - libpulse
  - libva-intel-driver
  - linux
  - linux-firmware
  - lsof
  - lvm2
  - man-db
  - man-pages
  - nano
  - neovim
  - network-manager-applet
  - networkmanager
  - pacman-contrib
  - openssh
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - polkit-kde-agent
  - pulsemixer
  - qt5-wayland
  - qt6-virtualkeyboard
  - qt6-wayland
  - reflector
  - rsync
  - sddm
  - slurp
  - smartmontools
  - sof-firmware
  - strace
  - telegram-desktop
  - thunar
  - tmux
  - tree
  - unzip
  - uwsm
  - vim
  - vulkan-intel
  - vulkan-nouveau
  - vulkan-radeon
  - waybar
  - wget
  - wireless_tools
  - wireplumber
  - wofi
  - xdg-desktop-portal-hyprland
  - xdg-user-dirs
  - xdg-utils
  - xf86-video-amdgpu
  - xf86-video-ati
  - xf86-video-nouveau
  - xorg-server
  - xorg-xinit
  - yazi
  - zram-generator
  - zsh

aur_packages:
  - clipse
  - google-chrome
  - rar

fonts:
  - ttf-jetbrains-mono
  - ttf-jetbrains-mono-nerd
