- name: Configure arch environment
  hosts: local

  roles:
    - name: host_info
      tags: ['host_info']

    - name: console
      tags: ['console']

    - name: timezone
      tags: ['timezone']

    - name: ntp
      tags: ['ntp']

    - name: locale
      tags: ['locale']

    - name: hostname
      tags: ['hostname']

    - name: initramfs
      tags: ['initramfs']

    - name: grub
      tags: ['grub']

    - name: pacman
      tags: ['pacman']

    - name: packages
      tags: ['packages']

    - name: users
      tags: ['users']

    - name: xdg
      tags: ['xdg']

    - name: performance
      tags: ['performance']
