- name: Configure arch environment
  hosts: local

  roles:
    - name: check
      tags: ['check']

    - name: console
      tags: ['console']

    - name: timezone
      tags: ['timezone']

    - name: ntp
      tags: ['ntp']

    - name: locale
      tags: ['locale']

    - name: hostname
      tags: ['hostname']

    - name: initramfs
      tags: ['initramfs']

    - name: grub
      tags: ['grub']

    - name: pacman
      tags: ['pacman']

    - name: packages
      tags: ['packages']

    - name: performance
      tags: ['performance']

    - name: users
      tags: ['users']

    - name: ssh
      tags: ['ssh']

    - name: gpg
      tags: ['gpg']

    - name: dotfiles
      tags: ['dotfiles']

    - name: xdg
      tags: ['xdg']
