- name: Configure arch environment
  hosts: local
  vars_files:
    - group_vars/local.yml
    - group_vars/secrets.yml

  roles:
    - name: ntp
      tags: ['ntp']

    - name: locale
      tags: ['locale']

    - name: hostname
      tags: ['hostname']

    - name: initramfs
      tags: ['initramfs']

    - name: grub
      tags: ['grub']

    - name: pacman
      tags: ['pacman']

    - name: packages
      tags: ['packages']

    - name: performance
      tags: ['performance']

    - name: users
      tags: ['users']

    - name: ssh
      tags: ['ssh']

    - name: gpg
      tags: ['gpg']

    - name: gopass
      tags: ['gopass']

    - name: dotfiles
      tags: ['dotfiles']

    - name: xdg
      tags: ['xdg']

    - name: sddm
      tags: ['sddm']

    - name: firewall
      tags: ['firewall']
