---
- name: Reload iptables
  ansible.builtin.service:
    name: iptables.service
    state: reloaded
  become: true

- name: Reload ip6tables
  ansible.builtin.service:
    name: ip6tables.service
    state: reloaded
  become: true
