---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml
  become: true

- name: Install font packages
  ansible.builtin.import_tasks: fonts.yml
  become: true

- name: Install AUR packages
  ansible.builtin.import_tasks: aur.yml
  become: true
