---
- name: Assert chezmoi_repo_url
  ansible.builtin.assert:
    that:
      - chezmoi_repo_url is defined
      - chezmoi_repo_url is string
      - chezmoi_repo_url | length > 0
    quiet: true

- name: Assert chezmoi_source_dir
  ansible.builtin.assert:
    that:
      - chezmoi_source_dir is defined
      - chezmoi_source_dir is string
      - chezmoi_source_dir | length > 0
    quiet: true

- name: Assert chezmoi_branch
  ansible.builtin.assert:
    that:
      - chezmoi_branch is defined
      - chezmoi_branch is string
      - chezmoi_branch | length > 0
    quiet: true
