---
# Server
# ======
#
# Basic configuration
ssh_server_enabled: false
ssh_server_ports: ['22']
network_ipv6_enable: false
ssh_listen_to: ['0.0.0.0']
# Security configuration
sshd_strict_modes: true
sshd_syslog_facility: 'AUTH'
sshd_log_level: 'INFO'
# Authentication
ssh_login_grace_time: 30s
ssh_max_auth_retries: 3
ssh_max_sessions: 3
sshd_authenticationmethods: 'publickey'
ssh_permit_root_login: false
ssh_authorized_keys_file: '.ssh/authorized_keys'
ssh_server_password_login: false
ssh_challengeresponseauthentication: false
# Network
ssh_client_alive_interval: 300
ssh_client_alive_count: 3
ssh_permit_tunnel: false
ssh_allow_tcp_forwarding: false
ssh_allow_agent_forwarding: false
ssh_gateway_ports: false
ssh_x11_forwarding: false
# User environment configuration
ssh_server_permit_environment_vars: false
ssh_server_accept_env_vars: ''
# Misc. configuration
ssh_compression: true
ssh_use_dns: false
ssh_print_motd: false
ssh_print_last_log: false
sftp_enabled: false

# Client
ssh_client_port: '22'
ssh_client_password_login: false
