---
- name: Copy pacman config
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: '644'

- name: Backup mirrorlist
  ansible.builtin.copy:
    src: "{{ mirrors_file }}"
    dest: "{{ mirrors_file }}.backup_{{ now(fmt='%y.%m.%d_%H:%M:%S') }}"
    remote_src: true
    owner: root
    group: root
    mode: '644'

- name: Install reflector
  community.general.pacman:
    name: reflector
    state: present
    update_cache: true

- name: Copy reflector config
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: "{{ reflector_conf_dir }}/reflector.conf"
    owner: root
    group: root
    mode: '644'

- name: Start and enable reflector.timer
  ansible.builtin.systemd_service:
    name: reflector.timer
    state: started
    enabled: true
    daemon_reload: true

- name: Start and enable reflector.service
  ansible.builtin.systemd_service:
    name: reflector.service
    state: started
    enabled: true
    daemon_reload: true

- name: Start and enable archlinux-keyring-wkd-sync.timer
  ansible.builtin.systemd_service:
    name: archlinux-keyring-wkd-sync.timer
    state: started
    enabled: true
    daemon_reload: true

- name: Start and enable archlinux-keyring-wkd-sync.service
  ansible.builtin.systemd_service:
    name: archlinux-keyring-wkd-sync.service
    state: started
    enabled: true
    daemon_reload: true
