#!/usr/bin/env bash
set -eu

script_name=$(basename "${BASH_SOURCE[0]}")
source envs/${script_name}.env

echo "LANG=${DEFAULT_LOCALE}" > ${LOCALE_CONF_FILE}

for lcl in ${LOCALES[@]}; do
    sed -i "/${lcl}/s/^#//" /etc/locale.gen
done

locale-gen
