#!/usr/bin/env bash
set -eu

script_name=$(basename "${BASH_SOURCE[0]}")
source envs/${script_name}.env

envsubst < ./templates/custom_initramfs.conf.tmpl > ${INITRAMFS_CONF_DIR}/custom.conf
mkinitcpio -P
