#!/usr/bin/env bash
set -eu

source ${ENV_FILE}

INITRAMFS_CONF_DIR="/etc/mkinitcpio.conf.d"
INITRAMFS_CONF_FILE="custom_initramfs.conf"

export HOOKS=$(arr_join ' ' ${INITRAMFS_HOOKS[@]})
export MODULES=$(arr_join ' ' ${INITRAMFS_MODULES[@]})

backup ${INITRAMFS_CONF_DIR}/${INITRAMFS_CONF_FILE}
envsubst < ${TEMPLATES_DIR}/${INITRAMFS_CONF_FILE}.tmpl > ${TEMP_DIR}/${INITRAMFS_CONF_FILE}
$SUDO mv ${TEMP_DIR}/${INITRAMFS_CONF_FILE} ${INITRAMFS_CONF_DIR}/${INITRAMFS_CONF_FILE}

$SUDO mkinitcpio -P
