#!/usr/bin/env bash
set -eu

source ${ENV_FILE}

CONF_DIR="/etc"
REFLECTOR_CONF_DIR="${CONF_DIR}/xdg/reflector"
PACMAN_CONF_DIR="${CONF_DIR}/pacman.d"
PACMAN_CONF_FILE="pacman.conf"
REFLECTOR_CONF_FILE="reflector.conf"
export PACMAN_MIRRORS_FILE="${PACMAN_CONF_DIR}/mirrorlist"

backup ${CONF_DIR}/${PACMAN_CONF_FILE}
backup ${REFLECTOR_CONF_DIR}/${REFLECTOR_CONF_FILE}

envsubst < ${TEMPLATES_DIR}/${PACMAN_CONF_FILE}.tmpl > ${TEMP_DIR}/${PACMAN_CONF_FILE}
envsubst < ${TEMPLATES_DIR}/${REFLECTOR_CONF_FILE}.tmpl > ${TEMP_DIR}/${REFLECTOR_CONF_FILE}

$SUDO mv ${TEMP_DIR}/${PACMAN_CONF_FILE} ${CONF_DIR}/${PACMAN_CONF_FILE}
$SUDO mv ${TEMP_DIR}/${REFLECTOR_CONF_FILE} ${REFLECTOR_CONF_DIR}/${REFLECTOR_CONF_FILE}

$SUDO pacman -Syu
$SUDO pacman -S --noconfirm reflector pacman-contrib
#$SUDO reflector --country Russia --sort rate --threads $(nproc) --ipv4 --save ${PACMAN_MIRRORS_FILE}

$SUDO pacman -S ${PACMAN_PACKAGES[@]}
