#!/usr/bin/env bash
set -eu

source ${ENV_FILE}
SUDO_CONF_DIR="/etc/sudoers.d"

if ! grep -q ${USER_NAME} /etc/passwd; then
    $SUDO useradd -m -s ${USER_SHELL} ${USER_NAME}
    $SUDO passwd ${USER_NAME}
fi

$SUDO usermod -G "" ${USER_NAME}
for group in ${USER_GROUPS[@]}; do
    $SUDO usermod -aG ${group} ${USER_NAME}
done

echo "%wheel ALL=(ALL:ALL) ALL" | $SUDO tee ${SUDO_CONF_DIR}/custom_sudoers
