#!/usr/bin/env bash
set -eu

source ${ENV_FILE}

AUR_HELPER="paru"
AUR_HELPER_REPO="https://aur.archlinux.org/paru.git"

if ! command -v ${AUR_HELPER} >/dev/null; then
    git clone ${AUR_HELPER_REPO} /tmp/${AUR_HELPER}
    chown ${USER_NAME}:${USER_NAME} /tmp/${AUR_HELPER}
    pushd /tmp/${AUR_HELPER}
    sudo -u ${USER_NAME} makepkg -si
    popd
fi

# Upgrade AUR packages and install new
sudo -u ${USER_NAME} ${AUR_HELPER} -Sua
sudo -u ${USER_NAME} ${AUR_HELPER} -S ${AUR_PACKAGES[@]}
