#!/usr/bin/env bash
set -eu

SYSCTL_CONF_DIR="/etc/sysctl.d"
SYSCTL_CONF_FILE="99-performance.conf"
ZRAM_CONF_DIR="/etc/systemd"
ZRAM_CONF_FILE="zram-generator.conf"
export ZRAM_DEVICE_NAME="zram0"
export SWAPPINESS=150

backup ${SYSCTL_CONF_DIR}/${SYSCTL_CONF_FILE}
backup ${ZRAM_CONF_DIR}/${ZRAM_CONF_FILE}

envsubst < ${TEMPLATES_DIR}/${SYSCTL_CONF_FILE}.tmpl > ${TEMP_DIR}/${SYSCTL_CONF_FILE}
envsubst < ${TEMPLATES_DIR}/${ZRAM_CONF_FILE}.tmpl > ${TEMP_DIR}/${ZRAM_CONF_FILE}

$SUDO mv ${TEMP_DIR}/${SYSCTL_CONF_FILE} ${SYSCTL_CONF_DIR}/${SYSCTL_CONF_FILE}
$SUDO mv ${TEMP_DIR}/${ZRAM_CONF_FILE} ${ZRAM_CONF_DIR}/${ZRAM_CONF_FILE}

$SUDO systemctl daemon-reload
$SUDO systemctl start systemd-zram-setup@${ZRAM_DEVICE_NAME}.service
$SUDO systemctl enable --now earlyoom.service
$SUDO systemctl enable --now irqbalance.service
$SUDO systemctl enable --now fstrim.timer
$SUDO sysctl -p ${SYSCTL_CONF_DIR}/${SYSCTL_CONF_FILE}
