#!/usr/bin/env bash
set -eu

GRUB_CONF_FILE="/etc/default/grub"
GRUB_THEME_DIR="/usr/share/grub/themes/custom-themes"

backup ${GRUB_CONF_FILE}

$SUDO sed -Ei 's/^(#)?GRUB_DEFAULT=.*$/GRUB_DEFAULT=0/' ${GRUB_CONF_FILE}
$SUDO sed -Ei 's/^(#)?GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=10/' ${GRUB_CONF_FILE}
$SUDO sed -Ei '/^(#)?GRUB_THEME=.*$/d' ${GRUB_CONF_FILE}

if (( ${GRUB_SET_THEME} )); then
    if [[ ! -d ${GRUB_THEME_DIR} ]]; then
        $SUDO git clone ${GRUB_THEMES_REPO} ${GRUB_THEME_DIR}
    fi
    pushd "${GRUB_THEME_DIR}/${GRUB_THEME_NAME}"
    $SUDO ./install.sh
    popd
fi

$SUDO grub-mkconfig -o /boot/grub/grub.cfg
