#!/usr/bin/env bash
set -euo pipefail

GPG_PRIVATE_KEY_FILE="private.gpg"

print_colored green "Enter passphrase for encrypting gpg private key.."
cat ${TEMPLATES_DIR}/encrypted_${GPG_PRIVATE_KEY_FILE} |
ansible-vault decrypt |
sudo -u ${USER_NAME} gpg --import
