#!/usr/bin/env bash
set -euo pipefail

print_colored green "Enter passphrase for encrypting gpg private key.."
cat ./templates/encrypted_private.gpg | ansible-vault decrypt > /tmp/private.gpg
gpg --import /tmp/private.gpg
rm /tmp/private.gpg
