#!/usr/bin/env bash
set -eu

GOPASS_STORE_PATH="/home/${USER_NAME}/.local/share/gopass/stores/root"
GOPASS_REPO_URL="git@github.com:ZaqWasder/pass.git"

if [[ ! -d ${GOPASS_STORE_PATH} ]]; then
    mkdir -p ${GOPASS_STORE_PATH}
    git clone ${GOPASS_REPO_URL} ${GOPASS_STORE_PATH}
fi
