#!/usr/bin/env bash
set -eu

CHEZMOI_REPO_URL="git@github.com:ZaqWasder/dotfiles.git"
CHEZMOI_BRANCH="hyprland-balcony-theme"


sudo -u ${USER_NAME} chezmoi init --branch ${CHEZMOI_BRANCH} --apply ${CHEZMOI_REPO_URL}
