#!/usr/bin/env bash
set -eu

script_name=$(basename "${BASH_SOURCE[0]}")
source envs/${script_name}.env
source envs/06_users.env

$SUDO mkdir -p ${SDDM_CONF_DIR}
envsubst < ./templates/sddm-autologin.conf.tmpl > /tmp/${SDDM_CONF_FILE_NAME}
$SUDO mv /tmp/${SDDM_CONF_FILE_NAME} ${SDDM_CONF_DIR}/${SDDM_CONF_FILE_NAME}
