#!/usr/bin/env bash
set -eu

SDDM_CONF_DIR="/etc/sddm.conf.d"
SDDM_CONF_FILE="autologin.conf"

$SUDO mkdir -p ${SDDM_CONF_DIR}
envsubst < ${TEMPLATES_DIR}/${SDDM_CONF_FILE}.tmpl > ${TEMP_DIR}/${SDDM_CONF_FILE}
$SUDO mv ${TEMP_DIR}/${SDDM_CONF_FILE} ${SDDM_CONF_DIR}/${SDDM_CONF_FILE}

$SUDO systemctl enable sddm.service
