---
- name: Include custom ssh config to default config
  block:
    - name: Remove curent Include
      ansible.builtin.lineinfile:
        path: "{{ ssh_default_conf_file }}"
        regexp: "^Include.*$"
        state: absent
    - name: Include custom ssh config
      ansible.builtin.lineinfile:
        path: "{{ ssh_default_conf_file }}"
        line: "Include {{ ssh_custom_conf_dir }}/*.conf"
        insertafter: EOF
        state: present

- name: Copy custom ssh config
  ansible.builtin.template:
    src: ssh.conf.j2
    dest: "{{ ssh_custom_conf_file }}"
    mode: "0644"
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
