---
- name: Copy motd script
  ansible.builtin.copy:
    src: files/generate_motd.sh
    dest: /usr/local/bin/generate_motd.sh
    owner: root
    group: root
    mode: '0755'

- name: Edit PAM configuration
  block:
    - name: Add motd file to /etc/pam.d/system-login
      ansible.builtin.lineinfile:
        path: /etc/pam.d/system-login
        regexp: '^(session.*optional.*pam_motd.so)'
        line: '\1          motd=/etc/motd'
        backrefs: true
    - name: Add motd generate script
      ansible.builtin.lineinfile:
        path: /etc/pam.d/system-login
        line: 'session    optional   pam_exec.so          /usr/local/bin/generate_motd.sh'
        insertbefore: '^session.*optional.*pam_motd.so'
        state: present
