---
- name: Install openssh
  ansible.builtin.import_tasks: install.yml
  become: true

- name: Configure openssh client
  ansible.builtin.import_tasks: configure_client.yml
  become: true

- name: Configure openssh server
  ansible.builtin.import_tasks: configure_server.yml
  become: true

- name: Configure motd
  ansible.builtin.import_tasks: configure_motd.yml
  become: true
  when: ssh_print_motd
