---
- name: Assert variables
  ansible.builtin.import_tasks: assert.yml

- name: Install gopass
  ansible.builtin.import_tasks: install.yml
  become: true

- name: Configure gopass
  ansible.builtin.import_tasks: configure.yml
