---
- name: Install packages
  community.general.pacman:
    name:
      - xdg-user-dirs
    state: present
    update_cache: true
  become: true

- name: Update xdg user dirs
  ansible.builtin.command:
    cmd: xdg-user-dirs-update
  register: xdg_command_result
  failed_when: xdg_command_result.rc != 0
