---
- name: Remove {{ iptables_conf_dir }} directory with all rules
  ansible.builtin.file:
    path: "{{ iptables_conf_dir }}"
    state: absent

- name: Create {{ iptables_conf_dir }} directory
  ansible.builtin.file:
    path: "{{ iptables_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Configure ipv4 iptables
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: "{{ iptables_conf_dir }}/iptables.rules"
    owner: root
    group: root
    mode: "644"
  notify:
    - Reload iptables

- name: Configure ipv6 iptables
  ansible.builtin.template:
    src: ip6tables.rules.j2
    dest: "{{ iptables_conf_dir }}/ip6tables.rules"
    owner: root
    group: root
    mode: "644"
  notify:
    - Reload ip6tables
