---
- name: Check distribution is supported
  ansible.builtin.assert:
    that: ansible_distribution == "Archlinux"
    fail_msg: "Distribution '{{ ansible_distribution }}' is not supported."
    success_msg: "I run on Arch, btw"

- name: Register required files status
  ansible.builtin.stat:
    path: "{{ check_temp_dir }}/{{ item }}"
  register: file_status
  loop: "{{ check_required_files }}"

- name: Fail if required files doesn't exists
  ansible.builtin.fail:
    msg: |
      One or more required files doesn't exists!
      List of required files:
        {{ check_required_files | ansible.builtin.join(', ') }}
  when: not item.stat.exists
  loop: "{{ file_status.results }}"
