---
- name: Create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.full_name }}"
    groups: "{{ item.additional_groups }}"
    shell: "{{ item.shell }}"
    create_home: "{{ item.create_home }}"
    append: "{{ item.append_groups }}"
    state: present
  become: true
  loop: "{{ users }}"
