# Basic configuration
# ===================

# Define which port sshd should listen to. Default to `22`.
Port ${SSH_SERVER_PORT}

# Address family should always be limited to the active network configuration.
AddressFamily inet

# Define which addresses sshd should listen to. Default to `0.0.0.0`, ie make sure you put your desired address in here, since otherwise sshd will listen to everyone.
ListenAddress ${SSH_SERVER_LISTEN_ADDRESS}


# Security configuration
# ======================

# Set the protocol version to 2 for security reasons. Disables legacy support.
Protocol 2

# Make sure sshd checks file modes and ownership before accepting logins. This prevents accidental misconfiguration.
StrictModes yes

# Logging, obsoletes QuietMode and FascistLogging
SyslogFacility AUTH
LogLevel INFO


# Authentication
# ==============

LoginGraceTime 30s
MaxAuthTries 3
MaxSessions 3

# Set AuthenticationMethods per default to publickey
AuthenticationMethods publickey

# Either disable or only allow root login via certificates.
PermitRootLogin ${PERMIT_ROOT_LOGIN}

PubkeyAuthentication yes

# Never use host-based authentication. It can be exploited.
IgnoreRhosts yes
IgnoreUserKnownHosts yes
HostbasedAuthentication no

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile .ssh/authorized_keys

# Disable password-based authentication, it can allow for potentially easier brute-force attacks.
PasswordAuthentication ${PASSWORD_AUTHENTICATION}
PermitEmptyPasswords no
ChallengeResponseAuthentication no


# Network
# =======

# Disable TCP keep alive since it is spoofable. Use ClientAlive messages instead, they use the encrypted channel
TCPKeepAlive no

# Manage `ClientAlive..` signals via interval and maximum count. This will periodically check up to a `..CountMax` number of times within `..Interval` timeframe, and abort the connection once these fail.
ClientAliveInterval 300
ClientAliveCountMax 3

# Disable tunneling
PermitTunnel no

# Disable forwarding tcp connections.
AllowTcpForwarding no

# Disable agent forwarding, since local agent could be accessed through forwarded connection.
AllowAgentForwarding no

# Port forwardings are forced to bind to the wildcard address
GatewayPorts no

# Disable X11 forwarding, since local X11 display could be accessed through forwarded connection.
X11Forwarding no
X11UseLocalhost yes


# User environment configuration
# ==============================

PermitUserEnvironment no

# Misc. configuration
# ===================

Compression yes
UseDNS no
PrintMotd no
