---
- name: Assert timezone variable
  ansible.builtin.assert:
    that:
      - timezone is defined
      - timezone | length > 0
    quiet: true

- name: Get timezone file info
  ansible.builtin.stat:
    path: "{{ timezone_dir }}/{{ timezone }}"
  register: timezone_file_info

- name: Assert that the file exists
  ansible.builtin.assert:
    that:
      - timezone_file_info.stat.exists
    quiet: true
    fail_msg: >
      File {{ timezone_dir }}/{{ timezone }} doesn't exist!
