---
- name: Set timezone
  ansible.builtin.file:
    src: "{{ timezone_dir }}/{{ timezone }}"
    dest: /etc/localtime
    owner: root
    group: root
    state: link

- name: Set hardware clock to UTC
  community.general.timezone:
    hwclock: UTC
