---
sshd_path: /usr/sbin/sshd
ssh_conf_dir: /etc/ssh
ssh_default_conf_file: "{{ ssh_conf_dir }}/ssh_config"
sshd_default_conf_file: "{{ ssh_conf_dir }}/sshd_config"
ssh_custom_conf_dir: "{{ ssh_conf_dir }}/ssh_config.d"
sshd_custom_conf_dir: "{{ ssh_conf_dir }}/sshd_config.d"
ssh_custom_conf_file: "{{ ssh_custom_conf_dir }}/99-ssh.conf"
sshd_custom_conf_file: "{{ sshd_custom_conf_dir }}/99-sshd.conf"
sshd_service_name: sshd
ssh_owner: root
ssh_group: root
