---
- name: Assert grub_default
  ansible.builtin.assert:
    that:
      - grub_default is defined
      - grub_default is number
      - grub_default >= 0
    quiet: true

- name: Assert grub_timeout
  ansible.builtin.assert:
    that:
      - grub_timeout is defined
      - grub_timeout is number
      - grub_timeout >= 0
    quiet: true

- name: Assert grub_update_command
  ansible.builtin.assert:
    that:
      - grub_update_command is defined
    quiet: true
