---
- name: Backup /etc/default/grub
  ansible.builtin.copy:
    src: "{{ grub_conf_file }}"
    dest: "{{ grub_conf_file }}.backup_{{ now(fmt='%y.%m.%d_%H:%M:%S') }}"
    remote_src: true
    owner: root
    group: root
    mode: '644'

- name: Configure grub
  notify:
    - Update grub
  block:
    - name: Change GRUB_DEFAULT
      ansible.builtin.lineinfile:
        path: "{{ grub_conf_file }}"
        regexp: '^(GRUB_DEFAULT=).*$'
        line: '\g<1>{{ grub_default }}'
        backrefs: true
    - name: Change GRUB_TIMEOUT
      ansible.builtin.lineinfile:
        path: "{{ grub_conf_file }}"
        regexp: '^(GRUB_TIMEOUT=).*$'
        line: '\g<1>{{ grub_timeout }}'
        backrefs: true
    - name: Change GRUB_CMDLINE_LINUX_DEFAULT
      ansible.builtin.lineinfile:
        path: "{{ grub_conf_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
        line: '\g<1> {{ grub_cmdline_linux_default }}"'
        backrefs: true
    - name: Change GRUB_CMDLINE_LINUX
      ansible.builtin.lineinfile:
        path: "{{ grub_conf_file }}"
        regexp: '^(GRUB_CMDLINE_LINUX=".*)"$'
        line: '\g<1> {{ grub_cmdline_linux }}"'
        backrefs: true
