---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  become: true

- name: Install grub
  ansible.builtin.import_tasks: install.yml
  become: true

- name: Configure grub
  ansible.builtin.import_tasks: configure.yml
  become: true

- name: Set grub theme
  ansible.builtin.import_tasks: theme.yml
  become: true

- name: Set grub password
  ansible.builtin.import_tasks: password.yml
  become: true
