---
- name: Encrypt grub password
  ansible.builtin.expect:
    command: grub-mkpasswd-pbkdf2
    responses:
      Enter password: "{{ grub_superuser_password }}"
      Reenter password: "{{ grub_superuser_password }}"
  no_log: true
  register: mkpasswd_result

- name: Set encrypted_grub_password
  ansible.builtin.set_fact:
    encrypted_grub_password: >-
      {{
        mkpasswd_result.stdout_lines
        | last
        | split
        | last
        | trim
      }}

- name: Debug encrypted password
  ansible.builtin.debug:
    msg: "{{ encrypted_grub_password }}"

- name: Copy /etc/grub.d/40_set_grub_password
  ansible.builtin.template:
    src: 40_set_grub_password.j2
    dest: /etc/grub.d/40_set_grub_password
    owner: root
    group: root
    mode: '755'
  notify:
    - Update grub
  changed_when: true
