---
- name: Copy /etc/grub.d/40_custom
  ansible.builtin.template:
    src: 40_custom.j2
    dest: /etc/grub.d/40_custom
    owner: root
    group: root
    mode: '755'
  notify:
    - Update grub
  when:
    - grub_set_password
    - grub_superuser is defined
    - grub_superuser_password is defined
  changed_when: true
