---
- name: Remove GRUB_THEME
  ansible.builtin.lineinfile:
    path: "{{ grub_conf_file }}"
    regexp: "^(#)?GRUB_THEME=.*$"
    state: absent
  when:
    - not grub_set_theme


- name: Clone repo with grub themes
  when:
    - grub_set_theme
    - grub_theme_dir is defined
    - grub_theme_name is defined
  block:
    - name: Create dir for grub themes
      ansible.builtin.file:
        path: "{{ grub_theme_dir }}"
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: Clone a repo with grub themes
      ansible.builtin.git:
        repo: "{{ grub_themes_repo_url }}"
        dest: "{{ grub_theme_dir }}"
        update: false


- name: Set grub theme
  block:
    - name: Find theme.txt in theme dir
      ansible.builtin.find:
        paths: "{{ grub_theme_dir }}/{{ grub_theme_name }}"
        file_type: file
        patterns: "theme.txt"
        recurse: true
        limit: 1
      register: find_result

    - name: Set path to theme.txt file
      ansible.builtin.set_fact:
        theme_txt_path: >-
          {{
            find_result.files
            | map(attribute='path')
            | first
          }}
      failed_when:
        - theme_txt_path | regex_search(' ')

    - name: Add GRUB_THEME variable to {{ grub_conf_file }}
      ansible.builtin.lineinfile:
        path: "{{ grub_conf_file }}"
        line: 'GRUB_THEME="{{ theme_txt_path }}"'
        insertafter: EOF
        state: present
